database:
  host: 127.0.0.1
  port: 3306
  user: raincandy_U
  password: angelkawaii2
  database: dylsemhokma


redis:
# Not Enabled Yet, ignore
  host: localhost
  port: 6379
  auth: root
  pass: root
  connect: 32
  timeout: 1000

